/**
 * Calculates the exact offset between the client's clock and the server's clock.
 * * @param clientSendTime - Date.now() right before making a Convex query
 * @param serverTime - Date.now() generated BY the Convex server and returned to client
 * @param clientReceiveTime - Date.now() right after the Convex query finishes
 * @returns The offset in milliseconds. Add this to client Date.now() to get Server time.
 */
export function calculateServerOffset(
    clientSendTime: number,
    serverTime: number,
    clientReceiveTime: number
): number {
    // Round Trip Time (RTT) is the total time the request took to go there and back
    const rtt = clientReceiveTime - clientSendTime;

    // Assume the network delay is symmetrical (it took half the RTT to get to the server)
    const networkLatency = rtt / 2;

    // The time the server *actually* processed it, minus what our clock thought it should be
    const offset = serverTime - (clientSendTime + networkLatency);

    return offset;
}

/**
 * Calculates the EXACT millisecond the audio should be at right now.
 * * @param serverStartTime - The timestamp the host pressed play (saved in Convex)
 * @param pausePosition - Where the song was paused (if it is paused)
 * @param isPlaying - Boolean from Convex
 * @param serverOffset - The offset calculated from `calculateServerOffset`
 * @returns The target `currentTime` in seconds for the <audio> tag
 */

export function getPerfectSyncTime(
    serverStartTime: number | undefined,
    pausePosition: number,
    isPlaying: boolean,
    serverOffset: number = 0 // Default to 0 if we haven't calculated it yet
): number {
    if (!isPlaying || !serverStartTime) {
        return pausePosition;
    }

    // What time is it right now on the Server?
    const currentServerTime = Date.now() + serverOffset;

    // How long has the song been playing since the host hit play?
    const elapsedMilliseconds = currentServerTime - serverStartTime;

    // Convert to seconds for HTML5 Audio
    return elapsedMilliseconds / 1000;
}