/**
 * Calculates the exact offset between the client's clock and the server's clock.
 * * @param clientSendTime - Date.now() right before making a Convex query
 * @param serverTime - Date.now() generated BY the Convex server and returned to client
 * @param clientReceiveTime - Date.now() right after the Convex query finishes
 * @returns The offset in milliseconds. Add this to client Date.now() to get Server time.
 */
export function calculateServerOffset(
  clientSendTime: number,
  serverTime: number,
  clientReceiveTime: number,
): number {
  const rtt = clientReceiveTime - clientSendTime;
  const networkLatency = rtt / 2;
  return serverTime - (clientSendTime + networkLatency);
}

/**
 * Calculates the EXACT millisecond the audio should be at right now.
 * * @param serverStartTime - The timestamp the host pressed play (saved in Convex)
 * @param pausePosition - Where the song was paused (if it is paused)
 * @param isPlaying - Boolean from Convex
 * @param serverOffset - The offset calculated from `calculateServerOffset`
 * @returns The target `currentTime` in seconds for the <audio> tag
 */

/**
 * Computes exact audio playback position in seconds.
 */
export function getPerfectSyncTime(
  serverStartTime: number | undefined,
  pausePosition: number,
  isPlaying: boolean,
  serverOffset: number = 0,
  durationSec: number = 0,
): number {
  if (!isPlaying || !serverStartTime) {
    return Math.max(0, pausePosition || 0);
  }

  const currentServerTime = Date.now() + serverOffset;
  const elapsedMs = currentServerTime - serverStartTime;
  const calculatedSec = Math.max(0, elapsedMs / 1000);

  if (durationSec > 0 && calculatedSec >= durationSec) {
    return durationSec;
  }

  return calculatedSec;
}